### ISSUE TITLE
How to compile flexdll with msvc64

### ISSUE THREAD

**Issue by saixmh** [alainfrisch/flexdll#19]
Does it need **Cygwin** or **MSYS** ?

**Comment by dra27** [comment]
You can compile the C part (`flexdll_msvc64.obj` and `flexdll_initer_msvc64.obj`) manually by running (from an appropriate Microsoft Visual Studio Command Prompt):
```cmd
cl /DMSVC /c /Foflexdll_msvc64.obj flexdll.c
cl /Foflexdll_initer_msvc64.obj flexdll_initer.c
```
No other software is required. If you want to compile flexlink as well, it's a few more commands, and you obviously need OCaml installed (4.03.0 for the latest git version; 3.12.0+ for 0.34):
```cmd
rc version.rc
ocamlopt -g -w -105 -o flexlink.exe -cclib "-link version.res" version.ml coff.ml cmdline.ml create_dll.ml reloc.ml
```
though note that this is much easier with Cygwin (or MSYS2), as you can run:
```bash
make CHAINS=msvc64 all
```

**Comment by alainfrisch** [comment]
@dra27 Thanks for the reply!

@saixmh Did you manage to build flexdll?

**Comment by saixmh** [comment]
@dra27 thanks.
@alainfrisch Yes, I once wanted to build it. But I used ```gcc``` at that moment.
