### ISSUE TITLE
flexdll_dlopen needs Unicode-aware version on Windows

### ISSUE THREAD

**Issue by nojb** [alainfrisch/flexdll#33]
`flexdll_dlopen` receives a `char *` argument (library filename) that gets passed to `LoadLibraryEx`/`LoadLibrary`.  

We need a version taking `wchar_t *` and calling `LoadLibraryExW`/`LoadLibraryW`.

Related to ocaml/ocaml#1200.

**Comment by alainfrisch** [comment]
A PR would be appreciated!

**Comment by nojb** [comment]
Fixed by #34.
