### ISSUE TITLE
Build against ocaml-4.08.0+beta3 fails

### ISSUE THREAD

**Issue by jakoblichtenberg** [alainfrisch/flexdll#71]
Build against ocaml-4.08.0+beta3 fails as Pervasives.compare is no longer available.  

This fix worked for my specific situation:
```
--- reloc.ml.orig	2019-04-24 09:44:22.081768600 -0700
+++ reloc.ml	2019-04-24 09:46:11.136207400 -0700
@@ -498,7 +498,7 @@
   let strings = Buffer.create 1024 in
   let strsym = Symbol.intern sect 0l in
   obj.symbols <- strsym :: (Symbol.export symname sect 0l) :: obj.symbols;
-  let exports = List.sort Pervasives.compare exports in
+  let exports = List.sort compare exports in
   (* The runtime library assumes that names are sorted! *)
   int_to_buf data (List.length exports);
   List.iter

```

**Comment by dra27** [comment]
The compat layer should be updated, but can I ask what you mean by "fails"?

**Comment by jakoblichtenberg** [comment]
Here you go:

```
>ocaml
        OCaml version 4.08.0+beta3

# Pervasives.compare;;
Line 1, characters 0-18:
1 | Pervasives.compare;;
    ^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
```

**Comment by dra27** [comment]
That's not failing, it's displaying a deprecation warning. So it's (quite reasonably) just the warning which is bothering you, not that there's a configuration somewhere where that is causing an actual error/failure?

**Comment by jakoblichtenberg** [comment]
I apologize. I agree.  It is indeed just a warning.

**Comment by jakoblichtenberg** [comment]
It this issue to be "fixed" or "by design" please?  I just want to get closure on what I should be expecting with upcoming ocaml release and flexdll

**Comment by jakoblichtenberg** [comment]
@dra27. May I ask for clarity on above?  Fix or not fix  If fix: is my change OK?

**Comment by dra27** [comment]
The warning will be displayed, as you observe.

Your fix works, but the reason it was written as `Pervasives.compare` is to be explicit that `compare` doesn't get accidentally shadowed. So it should really become `Stdlib.compare`. This will require an update to the compatibility files - `Compat407.ml` would need to be introduced with a module `Stdlib` containing the `compare` symbol.

**Comment by jakoblichtenberg** [comment]
Ok. So now what?

**Comment by dra27** [comment]
Either wait, or propose a patch!

**Comment by jakoblichtenberg** [comment]
Well.  I did propose a patch :-).  So I will wait.  Thank you David for your advice.
