### ISSUE TITLE
Support gcc "-Wl" linker pass through option

### ISSUE THREAD

**Issue by MSoegtropIMC** [alainfrisch/flexdll#72]
This is a follow up on the discussion on Coq PR 9729:

<https://github.com/coq/coq/pull/9279>

If flexlink would support -Wl as synonym for -link, libraries which use -Wl options could be compiled without changes in the build instructions on Windows.

I will provide a PR, but only for simple cases of the -Wl syntax.

**Comment by dra27** [comment]
This issue should now be fixed, with the more complex case addressed in #85
